(Source ppx)
(Cfg_str project_name tailwind-ppx)
(Cfg_str project_slug tailwind-ppx)
(Cfg_str project_description"A short, but powerful statement about your project")
(Cfg_str syntax Reason)
(Cfg_str package_manager Esy)
(Cfg_str test_framework Rely)
(Cfg_str ci_cd Github)
(Cfg_str author_name"Dylan Irlbeck")
(Cfg_str github_username dylanirlbeck)
(Cfg_str npm_username dylanirlbeck)