name: Lint and format Pull Request

on: [pull_request]

jobs:
  lint:
    name: lint lockdir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v1

      - name: Install esy
        run: npm install -g esy

      - name: Update lockdir
        run: |
          esy install
          git add esy.lock

      - name: Print esy cache
        id: print_esy_cache
        run: node .github/workflows/print_esy_cache.js

      - name: Try to restore dependencies cache
        id: deps-cache-macos
        uses: actions/cache@v1
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          key: ${{ matrix.os }}-${{ hashFiles('**/index.json')}}

      - name: format sources files
        run: |
          esy format
          git add "*.re" "*.ml"

      - name: Check that lock directory are up-to-date.
        run: git diff --exit-code --cached

      - name: Push if it is not
        if: failure()
        run: |
          git remote set-url --push origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git config user.name "Github Runner"
          git config user.email "runner@runner.github.com"
          git commit -am "Update lockdir"
          git status
          git push origin HEAD:$GITHUB_HEAD_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display status should be clean
        if: success()
        run: git status

      - uses: actions/github-script@0.3.0
        if: failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `I have updated your lock dirs and formatted the code. Please @${context.actor} pull the last commit before pushing any more changes.`
            });

